import type { BenchmarkData, SourceKind } from "../contracts/tracefold";
import { formatReduction } from "../contracts/tracefold";
import { Icon } from "./Icon";
import { StatusPill } from "./StatusPill";

export function BenchmarksView({ benchmark }: { benchmark: BenchmarkData }) {
  const evidence = benchmark.liveEvidence;
  if (!evidence) return <div className="view view--benchmarks"><header className="view-header"><div><span className="section-kicker">Benchmark evidence</span><h1>Live evidence unavailable.</h1><p>Committed benchmark data did not pass its UI contract check.</p></div></header></div>;
  return <div className="view view--benchmarks">
    <header className="view-header"><div><span className="section-kicker">Live measured · Phase 9</span><h1>Retained {evidence.pairedRetention.correct} of {evidence.pairedRetention.denominator} answers the full context answered correctly</h1><p>{benchmark.benchmarkVersion} · {evidence.modelId} · {benchmark.itemCount} items. Paired retention counts TraceFold-correct answers only among items full context answered correctly.</p></div></header>
    <section className="benchmark-alert" role="status"><Icon name="check" size={19} /><div><strong>{percent(evidence.pairedRetention.value, 4)} paired retention</strong><p>Wilson 95% interval: {percent(evidence.pairedRetention.wilsonLow, 4)} to {percent(evidence.pairedRetention.wilsonHigh, 4)}. Uncertainty remains visible.</p></div></section>
    <section className="benchmark-facts" aria-label="Live benchmark results"><Fact value={`${evidence.fullContext.correct}/${evidence.fullContext.denominator}`} label="Full context" note="absolute accuracy" /><Fact value={`${evidence.cprgc.correct}/${evidence.cprgc.denominator}`} label="TraceFold" note="absolute accuracy" /><Fact value={`${evidence.successfulRequests}`} label="Successful live requests" note={`${evidence.infrastructureFailures} infrastructure failures`} /><Fact value="Not configured" label="Monetary cost" note="no production-cost claim" /></section>
    <section className="benchmark-table-panel" aria-labelledby="retention-table-title"><div className="panel-heading"><div><span className="section-kicker">Answer retention</span><h2 id="retention-table-title">Paired retention by source kind</h2></div><span className="panel-note">Denominator: full-context-correct items.</span></div><div className="benchmark-table" role="table" aria-label="Paired retention by source kind"><div className="benchmark-row benchmark-row--header" role="row"><span>Source kind</span><span>Retained</span><span>Rate</span><span>Scope</span></div>{sourceOrder.map((kind) => { const item = evidence.perSourceRetention[kind]; return <div className="benchmark-row" role="row" key={kind}><strong>{kind === "json" ? "JSON" : kind}</strong><span>{item.correct}/{item.denominator}</span><div><strong>{percent(item.correct / item.denominator, 1)}</strong><small>{kind === "python" ? "among full-correct cases" : "paired retention"}</small></div><StatusPill tone={item.correct === item.denominator ? "verified" : "warning"}>{item.correct === item.denominator ? "retained" : "disagreement"}</StatusPill></div>; })}</div></section>
    <section className="benchmark-table-panel" aria-labelledby="compression-table-title"><div className="panel-heading"><div><span className="section-kicker">Configured context reduction</span><h2 id="compression-table-title">Compression is separate from answer retention</h2></div><span className="panel-note">{benchmark.tokenizerIdentity}</span></div><div className="benchmark-table" role="table" aria-label="Configured context reduction by source kind"><div className="benchmark-row benchmark-row--header" role="row"><span>Source kind</span><span>Items</span><span>Reduction</span><span>Result</span></div>{sourceOrder.map((kind) => { const metric = benchmark.structuralReductionByKind[kind]; const python = kind === "python"; return <div className="benchmark-row" role="row" key={kind}><strong>{kind === "json" ? "JSON" : kind}</strong><span>{benchmark.sourceKindDistribution[kind]}</span><div><strong>{python ? "Incompressible" : formatReduction(metric)}</strong><small>{python ? "protected mandatory floor" : "configured cl100k_base context"}</small></div><StatusPill tone={python ? "warning" : "verified"}>{python ? "full source retained" : "compressed"}</StatusPill></div>; })}</div></section>
    <section className="benchmark-status-grid"><div className="status-block"><span className="section-kicker">Aggregate accounting</span><h2>Measured separately</h2><dl><dt>Mean emitted-context reduction</dt><dd>{percent(evidence.emittedContextReduction, 4)}</dd><dt>Fallback-adjusted aggregate</dt><dd>{percent(evidence.fallbackAdjustedReduction, 4)}</dd><dt>Provider request-input reduction</dt><dd>{percent(evidence.providerRequestInputReduction, 6)}</dd><dt>Provider input usage</dt><dd>{evidence.providerUsage.fullInput.toLocaleString("en-US")} full · {evidence.providerUsage.cprgcInput.toLocaleString("en-US")} TraceFold</dd><dt>Provider output usage</dt><dd>{evidence.providerUsage.fullOutput} full · {evidence.providerUsage.cprgcOutput} TraceFold</dd></dl></div><div className="status-block"><span className="section-kicker">Python mandatory floor</span><h2>Incompressible at protected mandatory floor</h2><p>TraceFold retained the full source rather than remove protected code evidence. No positive final savings are credited.</p></div></section>
    <section className="rules-panel" aria-labelledby="limits-title"><div className="panel-heading"><div><span className="section-kicker">Evidence limits</span><h2 id="limits-title">Where the evidence failed</h2></div><span className="panel-note">Structural verification does not guarantee every target-model answer.</span></div><div className="rule-list">{evidence.failureTriage.map((finding) => <article className="rule-row" key={finding.itemId}><div className="rule-status"><StatusPill tone="warning">{finding.category}</StatusPill><code>{finding.itemId}</code></div><div className="rule-body"><p>{finding.summary}</p></div></article>)}</div></section>
    <footer className="benchmark-footnote"><Icon name="lock" size={15} />Four compressible source classes exceeded 70% configured context reduction. No universal accuracy, all-workload reduction, or semantic-equivalence claim is made.</footer>
  </div>;
}

const sourceOrder: SourceKind[] = ["dialogue", "document", "json", "log", "python"];

function percent(value: number, digits: number): string { return `${(value * 100).toFixed(digits)}%`; }
function Fact({ value, label, note }: { value: string; label: string; note: string }) { return <div className="benchmark-fact"><strong>{value}</strong><span>{label}</span><small>{note}</small></div>; }
