import type { BenchmarkData } from "../contracts/tracefold";
import { formatReduction, reductionLabel, retentionLabel } from "../contracts/tracefold";
import { Icon } from "./Icon";
import { StatusPill } from "./StatusPill";

export function BenchmarksView({ benchmark }: { benchmark: BenchmarkData }) {
  return <div className="view view--benchmarks">
    <header className="view-header"><div><span className="section-kicker">Benchmark preparation</span><h1>Prepared artifacts. No accuracy score yet.</h1><p>ContextProofBench is ready for paired evaluation, but no target-model answers have been measured.</p></div></header>
    <section className="benchmark-alert" role="status"><Icon name="alert" size={19} /><div><strong>Downstream accuracy is unmeasured</strong><p>No live or valid replay responses exist, so TraceFold shows no accuracy chart and never converts missing values to zero.</p></div></section>
    <section className="benchmark-facts" aria-label="Benchmark preparation facts"><Fact value={benchmark.itemCount.toString()} label="ContextProofBench items" note="10 per source kind" /><Fact value={Object.keys(benchmark.sourceKindDistribution).length.toString()} label="Source kinds" note="document · dialogue · JSON · logs · Python" /><Fact value={benchmark.preparedMethodCount.toString()} label="Prepared methods" note="matched-budget methods" /><Fact value={benchmark.expectedRequestCount.toString()} label="Expected requests" note={`${benchmark.liveRequestCount} live requests`} /></section>
    <section className="benchmark-table-panel" aria-labelledby="kind-table-title"><div className="panel-heading"><div><span className="section-kicker">Structural evidence</span><h2 id="kind-table-title">Reduction by source kind</h2></div><span className="panel-note">Fixture-byte metrics are not production tokens.</span></div><div className="benchmark-table" role="table" aria-label="Structural reduction by source kind"><div className="benchmark-row benchmark-row--header" role="row"><span>Source kind</span><span>Prepared items</span><span>Metric</span><span>Scope</span></div>{Object.entries(benchmark.structuralReductionByKind).map(([kind, metric]) => <div className="benchmark-row" role="row" key={kind}><strong>{kind}</strong><span>{benchmark.sourceKindDistribution[kind as keyof typeof benchmark.sourceKindDistribution]}</span><div><strong>{formatReduction(metric)}</strong><small>{reductionLabel(metric)}</small></div><StatusPill tone="info">structural only</StatusPill></div>)}</div></section>
    <section className="benchmark-status-grid"><div className="status-block"><span className="section-kicker">Accounting</span><h2>What is counted</h2><dl><dt>Tokenizer accounting</dt><dd>{benchmark.tokenizerAccounting.replaceAll("_", " ")}</dd><dt>Identity</dt><dd>{benchmark.tokenizerIdentity}</dd><dt>Downstream retention</dt><dd>{retentionLabel(benchmark.downstreamRetention)}</dd><dt>Pricing</dt><dd>{benchmark.pricingStatus === "unset" ? "Not configured" : "Configured"}</dd><dt>Infrastructure</dt><dd>{benchmark.infrastructureStatus}</dd></dl></div><div className="status-block status-block--empty"><span className="section-kicker">Future scored fields</span><h2>Awaiting target responses</h2><p>Once live or replay data exists, this contract can render full-context accuracy, CPRGC accuracy, paired retention, per-source retention, baseline comparison, compression, latency, cost, and failure counts.</p><div className="future-field-list">{[["Full-context accuracy", benchmark.futureMetrics.fullContextAccuracy], ["CPRGC accuracy", benchmark.futureMetrics.cprgcAccuracy], ["Paired retention", benchmark.futureMetrics.pairedRetention], ["Latency / cost", benchmark.futureMetrics.latency ?? benchmark.futureMetrics.cost]].map(([label, value]) => <div key={label as string}><span>{label as string}</span><strong>{value === null ? "Unmeasured" : `${Number(value) * 100}%`}</strong></div>)}</div></div></section>
    <footer className="benchmark-footnote"><Icon name="lock" size={15} />{benchmark.notes.join(" ")}</footer>
  </div>;
}

function Fact({ value, label, note }: { value: string; label: string; note: string }) { return <div className="benchmark-fact"><strong>{value}</strong><span>{label}</span><small>{note}</small></div>; }
