import type { CertificateData, DemoScenario } from "../contracts/tracefold";
import { coverageLabel, coveragePercent, hashLabel } from "../contracts/tracefold";
import { Icon } from "./Icon";
import { StatusPill } from "./StatusPill";
import { statusTone } from "./statusTone";

export function ProofView({ scenario }: { scenario: DemoScenario }) {
  const certificate = scenario.certificate;
  return <div className="view view--proof">
    <header className="view-header"><div><span className="section-kicker">Proof inspector</span><h1>Verify the compact artifact independently.</h1><p>Inspect the certificate, preservation coverage, and verifier observations. This is structural evidence—not downstream answer accuracy.</p></div><StatusPill tone={statusTone(certificate.status)}>{certificate.status === "valid" ? "Independent verification passed" : certificate.status.replaceAll("_", " ")}</StatusPill></header>
    <section className="proof-trust-line" aria-label="Trust boundary"><BoundaryStep tone="compressor" label="Compressor proposes" /><span className="boundary-arrow">/</span><BoundaryStep tone="certificate" label="Certificate records" /><span className="boundary-arrow">/</span><BoundaryStep tone="verifier" label="Verifier recomputes" /><span className="boundary-arrow">/</span><BoundaryStep tone="recovery" label="Recovery repairs" /></section>
    <section className="identity-panel" aria-labelledby="identity-title"><div className="panel-heading"><div><span className="section-kicker">Bound artifacts</span><h2 id="identity-title">Identity</h2></div><span className="panel-note">Hash values are labels, not semantic claims.</span></div><div className="hash-grid"><HashRow label="Source hash" value={certificate.identity.sourceHash} /><HashRow label="Normalized source hash" value={certificate.identity.normalizedSourceHash} /><HashRow label="Compressed artifact hash" value={certificate.identity.compressedArtifactHash} /><HashRow label="Certificate hash" value={certificate.identity.certificateHash} /><HashRow label="Query hash" value={certificate.identity.queryHash} /><HashRow label="Tokenizer identity" value={certificate.identity.tokenizerIdentity} copyable={false} /></div><details className="component-details"><summary>Component versions <Icon name="chevron" size={15} /></summary><div>{Object.entries(certificate.identity.componentVersions).map(([key, value]) => <div key={key}><span>{key}</span><code>{value}</code></div>)}</div></details></section>
    <section className="coverage-panel" aria-labelledby="coverage-title"><div className="panel-heading"><div><span className="section-kicker">Coverage / denominator-aware</span><h2 id="coverage-title">Preservation coverage</h2></div><span className="panel-note">Zero discovered relations are not a 100% result.</span></div><div className="coverage-grid"><CoverageBlock label="Obligations verified" metric={certificate.obligations} /><CoverageBlock label="Source-map coverage" metric={certificate.sourceMap} /><div className="coverage-block"><span>Relation classes</span><strong>{certificate.relations.length ? `${certificate.relations.filter((item) => item.status === "passed").length}/${certificate.relations.length}` : "Not applicable"}</strong><small>exact and inferred classes listed below</small></div></div><div className="relation-table" role="table" aria-label="Relation verification results"><div className="relation-row relation-row--header" role="row"><span>Relation class</span><span>Discovered</span><span>Verified</span><span>Status</span></div>{certificate.relations.map((relation) => <div className="relation-row" role="row" key={relation.className}><code>{relation.className}</code><span>{relation.discovered ?? "Unreported"}</span><span>{relation.discovered === 0 ? "Not applicable" : relation.verified ?? "Unreported"}</span><StatusPill tone={statusTone(relation.status)}>{relation.status.replaceAll("_", " ")}</StatusPill></div>)}</div></section>
    <section className="rules-panel" aria-labelledby="rules-title"><div className="panel-heading"><div><span className="section-kicker">Verifier rules / failure-aware</span><h2 id="rules-title">Verification rules</h2></div><span className="panel-note">Observed conditions come from independent checks.</span></div><div className="rule-list">{certificate.rules.map((rule) => <article className={`rule-row rule-row--${rule.status}`} key={rule.id}><div className="rule-status"><StatusPill tone={statusTone(rule.status)}>{rule.status.replaceAll("_", " ")}</StatusPill><code>{rule.id}</code></div><div className="rule-body"><div><span>Expected</span><p>{rule.expected}</p></div><div><span>Observed</span><p>{rule.observed}</p></div><div><span>Evidence spans</span><code>{rule.evidenceSpanIds.length ? rule.evidenceSpanIds.join(", ") : "none"}</code></div><div><span>Recommended action</span><p>{rule.recommendation}</p></div></div></article>)}</div>{certificate.failedInvariants.length ? <div className="failed-list" role="alert"><Icon name="alert" size={17} /><div><strong>Failed invariants retained in recovery history</strong>{certificate.failedInvariants.map((failure) => <code key={failure}>{failure}</code>)}</div></div> : null}</section>
    <section className="claim-note"><Icon name="lock" size={18} /><div><strong>Trust boundary</strong><p>{certificate.note}</p><span>Target-model evaluation sits outside structural verification. Current downstream retention: <b>Unmeasured</b>.</span></div></section>
  </div>;
}

function BoundaryStep({ tone, label }: { tone: string; label: string }) { return <div className={`boundary-step boundary-step--${tone}`}><span className="boundary-step__dot" /><span>{label}</span></div>; }

function HashRow({ label, value, copyable = true }: { label: string; value: string | null; copyable?: boolean }) {
  return <div className="hash-row"><span>{label}</span><code aria-label={`${label}: ${hashLabel(value)}`}>{hashLabel(value)}</code>{copyable && value ? <button className="icon-button" type="button" aria-label={`Copy ${label}`} onClick={() => void navigator.clipboard?.writeText(value)}><Icon name="copy" size={15} /></button> : null}</div>;
}

function CoverageBlock({ label, metric }: { label: string; metric: CertificateData["obligations"] }) { return <div className="coverage-block"><span>{label}</span><strong>{coveragePercent(metric)}</strong><small>{coverageLabel(metric)} · {metric.denominatorMeaning}</small></div>; }
