import type { DemoScenario, RecoveryStage } from "../contracts/tracefold";
import { displayCount, formatReduction, reductionLabel } from "../contracts/tracefold";
import { Icon } from "./Icon";
import { StatusPill } from "./StatusPill";
import { statusTone } from "./statusTone";

export function RecoveryView({ scenario }: { scenario: DemoScenario }) {
  const recovery = scenario.recovery;
  return <div className="view view--recovery">
    <header className="view-header"><div><span className="section-kicker">Recovery history</span><h1>Recover without hiding failure.</h1><p>Restore exact source spans, expand the budget, or return the full context. Every failed attempt remains visible.</p></div><div className="view-header__stamp"><span>Demo scenario</span><strong>{scenario.fixtureIdentity}</strong></div></header>
    {!recovery ? <section className="empty-state"><Icon name="recovery" size={24} /><h2>No recovery was needed</h2><p>This artifact passed verification without restoration. Choose the recovery scenario to inspect a recorded failure and fallback.</p></section> : <>
      <section className="recovery-summary"><div><span className="section-kicker">Final decision</span><strong>{recovery.finalAction.replaceAll("_", " ")}</strong><p>{recovery.note}</p></div><div className="recovery-summary__metric"><span>Final reduction</span><strong>{formatReduction(recovery.finalReduction)}</strong><small>{reductionLabel(recovery.finalReduction)}</small></div><StatusPill tone={statusTone(recovery.finalAction)}>{recovery.finalAction === "full_fallback" ? "Zero final savings" : recovery.finalAction.replaceAll("_", " ")}</StatusPill></section>
      <section className="timeline-panel" aria-labelledby="timeline-title"><div className="panel-heading"><div><span className="section-kicker">{recovery.sourceFixture}</span><h2 id="timeline-title">{recovery.stages.length} recorded recovery stages</h2></div><span className="panel-note">{scenario.valuesSynthetic ? "Prepared fixture policy; no runtime event claimed." : "Only recorded hashes and budgets are shown."}</span></div><ol className="recovery-timeline">{recovery.stages.map((stage) => <TimelineItem key={stage.number} stage={stage} />)}</ol></section>
      <section className="failure-panel" aria-labelledby="failure-title"><div className="failure-panel__heading"><StatusPill tone="failed">Failed invariant / preserved history</StatusPill><h2 id="failure-title">{recovery.rawFailure}</h2></div><div className="failure-panel__body"><div><span>What happened</span><p>Mandatory evidence could not fit inside requested budget. TraceFold did not label the raw attempt as a successful compression.</p></div><div><span>Next action</span><p>{recovery.finalAction === "full_fallback" ? "Return exact full context; final reduction is 0%." : `Selected action: ${recovery.finalAction.replaceAll("_", " ")}.`}</p></div><div><span>Evidence scope</span><p>{scenario.evidenceScope}</p></div></div></section>
    </>}
  </div>;
}

function TimelineItem({ stage }: { stage: RecoveryStage }) {
  const count = stage.count === null ? "Not recorded" : displayCount({ value: stage.count, source: stage.countSource ?? "fixture_bytes", counterIdentity: stage.countSource === "configured_tokenizer" ? "configured tokenizer" : "fixture byte counter · v1", synthetic: true });
  return <li className={`timeline-item timeline-item--${stage.status}`}><div className="timeline-item__rail"><span className="timeline-item__number">{String(stage.number).padStart(2, "0")}</span><span className="timeline-item__dot" /></div><article><header><div><span className="timeline-item__label">{stage.label}</span><StatusPill tone={statusTone(stage.status)}>{stage.status.replaceAll("_", " ")}</StatusPill></div><code>{stage.artifactHash ?? "artifact hash not recorded"}</code></header><div className="timeline-item__details"><span><b>Budget</b>{stage.effectiveBudget === null ? "Not recorded" : stage.effectiveBudget.toLocaleString("en-US")}</span><span><b>Action</b>{stage.action.replaceAll("_", " ")}</span><span><b>Count</b>{count}</span><span><b>Verification</b>{stage.verification.replaceAll("_", " ")}</span></div>{stage.failedInvariants.length ? <div className="timeline-item__failures"><Icon name="alert" size={14} />{stage.failedInvariants.join(" · ")}</div> : null}{stage.restoredSpans.length ? <div className="timeline-item__restored"><Icon name="check" size={14} />Restored: {stage.restoredSpans.join(", ")}</div> : null}<p>{stage.note}</p>{stage.historyHash ? <code className="timeline-item__history">Recovery-history hash · {stage.historyHash}</code> : null}</article></li>;
}
